services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
      - ../mlflow.db:/app/mlflow.db
    restart: unless-stopped