/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAiInsightsRouteImport } from './routes/dashboard.ai-insights'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardCityComparisonRouteImport } from './routes/dashboard.city-comparison'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardModelMonitorRouteImport } from './routes/dashboard.model-monitor'
import { Route as DashboardPredictionRouteImport } from './routes/dashboard.prediction'
import { Route as DashboardRoutePlannerRouteImport } from './routes/dashboard.route-planner'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardWeatherRouteImport } from './routes/dashboard.weather'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiInsightsRoute = DashboardAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCityComparisonRoute = DashboardCityComparisonRouteImport.update({
  id: '/city-comparison',
  path: '/city-comparison',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardModelMonitorRoute = DashboardModelMonitorRouteImport.update({
  id: '/model-monitor',
  path: '/model-monitor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionRoute = DashboardPredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoutePlannerRoute = DashboardRoutePlannerRouteImport.update({
  id: '/route-planner',
  path: '/route-planner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeatherRoute = DashboardWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-insights': typeof DashboardAiInsightsRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/city-comparison': typeof DashboardCityComparisonRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/model-monitor': typeof DashboardModelMonitorRoute
  '/dashboard/prediction': typeof DashboardPredictionRoute
  '/dashboard/route-planner': typeof DashboardRoutePlannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ai-insights': typeof DashboardAiInsightsRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/city-comparison': typeof DashboardCityComparisonRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/model-monitor': typeof DashboardModelMonitorRoute
  '/dashboard/prediction': typeof DashboardPredictionRoute
  '/dashboard/route-planner': typeof DashboardRoutePlannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai-insights': typeof DashboardAiInsightsRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/city-comparison': typeof DashboardCityComparisonRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/model-monitor': typeof DashboardModelMonitorRoute
  '/dashboard/prediction': typeof DashboardPredictionRoute
  '/dashboard/route-planner': typeof DashboardRoutePlannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/ai-insights'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/city-comparison'
    | '/dashboard/map'
    | '/dashboard/model-monitor'
    | '/dashboard/prediction'
    | '/dashboard/route-planner'
    | '/dashboard/settings'
    | '/dashboard/weather'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ai-insights'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/city-comparison'
    | '/dashboard/map'
    | '/dashboard/model-monitor'
    | '/dashboard/prediction'
    | '/dashboard/route-planner'
    | '/dashboard/settings'
    | '/dashboard/weather'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/ai-insights'
    | '/dashboard/alerts'
    | '/dashboard/analytics'
    | '/dashboard/city-comparison'
    | '/dashboard/map'
    | '/dashboard/model-monitor'
    | '/dashboard/prediction'
    | '/dashboard/route-planner'
    | '/dashboard/settings'
    | '/dashboard/weather'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai-insights': {
      id: '/dashboard/ai-insights'
      path: '/ai-insights'
      fullPath: '/dashboard/ai-insights'
      preLoaderRoute: typeof DashboardAiInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/city-comparison': {
      id: '/dashboard/city-comparison'
      path: '/city-comparison'
      fullPath: '/dashboard/city-comparison'
      preLoaderRoute: typeof DashboardCityComparisonRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/model-monitor': {
      id: '/dashboard/model-monitor'
      path: '/model-monitor'
      fullPath: '/dashboard/model-monitor'
      preLoaderRoute: typeof DashboardModelMonitorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prediction': {
      id: '/dashboard/prediction'
      path: '/prediction'
      fullPath: '/dashboard/prediction'
      preLoaderRoute: typeof DashboardPredictionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/route-planner': {
      id: '/dashboard/route-planner'
      path: '/route-planner'
      fullPath: '/dashboard/route-planner'
      preLoaderRoute: typeof DashboardRoutePlannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weather': {
      id: '/dashboard/weather'
      path: '/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof DashboardWeatherRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiInsightsRoute: typeof DashboardAiInsightsRoute
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCityComparisonRoute: typeof DashboardCityComparisonRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardModelMonitorRoute: typeof DashboardModelMonitorRoute
  DashboardPredictionRoute: typeof DashboardPredictionRoute
  DashboardRoutePlannerRoute: typeof DashboardRoutePlannerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWeatherRoute: typeof DashboardWeatherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiInsightsRoute: DashboardAiInsightsRoute,
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCityComparisonRoute: DashboardCityComparisonRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardModelMonitorRoute: DashboardModelMonitorRoute,
  DashboardPredictionRoute: DashboardPredictionRoute,
  DashboardRoutePlannerRoute: DashboardRoutePlannerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWeatherRoute: DashboardWeatherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
